name: ume_kit_slow_animation
description: Make the animation slow or fast.
version: 0.0.2
homepage: https://github.com/ume-community/ume

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ume: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
