name: example
description: A new Flutter project.
version: 1.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  # For Dio Kit
  dio: ^4.0.0
  ume: 0.2.1
  ume_kit_ui: 0.2.1
  ume_kit_perf: 0.2.1
  ume_kit_show_code: 0.2.1
  ume_kit_device: 0.2.1
  ume_kit_console: 0.2.1
  ume_kit_dio: 0.2.0

dependency_overrides:
  #[Original]: vm_service: ^9.4.0
  vm_service: ^14.2.5
  ume:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: ^1.16.6
  ume:
    path: ../
  ume_kit_ui:
    path: ../kits/ume_kit_ui
  ume_kit_perf:
    path: ../kits/ume_kit_perf
  ume_kit_show_code:
    path: ../kits/ume_kit_show_code
  ume_kit_device:
    path: ../kits/ume_kit_device
  ume_kit_console:
    path: ../kits/ume_kit_console
  ume_kit_dio:
    path: ../kits/ume_kit_dio
  ume_kit_channel_monitor:
    path: ../kits/ume_kit_channel_monitor

flutter:
  uses-material-design: true
