name: ume_kit_database_kit
description: Database kit for SQLite, hive and SP.
version: 0.0.2
homepage: https://github.com/ume-community/ume
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  # flutter: ">=1.17.0"

dependencies:
  data_table_2: ^2.2.1
  flutter:
    sdk: flutter
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.13
  sqflite: ^2.0.2+1
  translator: ^1.0.0
  path: any

  ume_core:
    path: ../ume_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
