name: ume_kit_designer_check
description: UI check tool for designer.
version: 0.0.2
homepage: https://github.com/ume-community/ume

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ume: ^2.0.0
  image_picker: ^0.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
