name: ume_kit_channel_observer
description: A new flutter plugin project.
version: 0.0.1
homepage: https://github.com/ume-community/ume

environment:
  sdk: ">=3.0.0 <4.0.0"
  # flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  ume: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.lijiaqi.ume_kit_channel_observer
        pluginClass: UmeKitChannelObserverPlugin
      ios:
        pluginClass: UmeKitChannelObserverPlugin

  assets:
    - assets/channel.png
