name: ume_kit_shared_preferences
description: Kit for shared_preferences.
version: 0.0.2
homepage: https://github.com/ume-community/ume
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: "^2.0.7"
  cupertino_icons: ^1.0.2

  ume_core:
    path: ../ume_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.12

flutter:
  uses-material-design: true
