name: ume_kit_show_code
description: Show Code kit for ume.
version: 2.0.0
homepage: https://github.com/ume-community/ume

environment:
  #[Original] sdk: ">=2.12.0 <3.0.0"
  #[Original] flutter: ">=2.0.0"
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ume: ^2.0.0
  share: ^2.0.4
  #[Original]: vm_service: ^9.4.0
  vm_service: ^14.2.5
  string_scanner: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.12
  flutter_coverage_badge:
    git:
      url: https://github.com/smileShirely/flutter_coverage_badge.git
      ref: 59b7580f406bb712e9d9049c8c99212946e34f65

flutter:
  uses-material-design: true
